In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
team_game_stats = pd.read_csv("../data/raw/team_stats.csv")
team_game_advanced = pd.read_csv("../data/raw/team_stats_advanced.csv")

team_game_stats.head()

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,teamScore,opponentScore,assists,blocks,steals,fieldGoalsAttempted,fieldGoalsMade,fieldGoalsPercentage,threePointersAttempted,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,numMinutes,q1Points,q2Points,q3Points,q4Points,benchPoints,biggestLead,biggestScoringRun,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId
0,22500827,2026-02-22 21:00:00,LA,Clippers,1610612746,Orlando,Magic,1610612753,1,0.0,109,111,18.0,9.0,9.0,83.0,40.0,0.482,23.0,5.0,0.217,28.0,24.0,0.857,34.0,9.0,43.0,18.0,9.0,-2.0,240.0,25.0,28.0,36.0,20.0,42.0,4.0,7.0,19.0,19.0,14.0,60.0,17.0,14.0,0.0,27.0,30.0,NaN
1,22500827,2026-02-22 21:00:00,Orlando,Magic,1610612753,LA,Clippers,1610612746,0,1.0,111,109,25.0,3.0,7.0,83.0,40.0,0.482,23.0,8.0,0.348,31.0,23.0,0.742,31.0,12.0,43.0,21.0,12.0,2.0,240.0,29.0,28.0,31.0,23.0,20.0,8.0,7.0,19.0,17.0,13.0,54.0,13.0,14.0,0.0,30.0,26.0,NaN
2,22500825,2026-02-22 20:00:00,Chicago,Bulls,1610612741,New York,Knicks,1610612752,1,0.0,99,105,24.0,2.0,8.0,86.0,34.0,0.395,46.0,16.0,0.348,21.0,15.0,0.714,37.0,13.0,50.0,17.0,17.0,-6.0,240.0,27.0,26.0,25.0,21.0,43.0,8.0,8.0,8.0,16.0,21.0,32.0,14.0,3.0,0.0,24.0,34.0,NaN
3,22500825,2026-02-22 20:00:00,New York,Knicks,1610612752,Chicago,Bulls,1610612741,0,1.0,105,99,27.0,4.0,9.0,84.0,38.0,0.452,42.0,15.0,0.357,21.0,14.0,0.667,40.0,10.0,50.0,17.0,13.0,6.0,240.0,25.0,27.0,31.0,22.0,27.0,13.0,8.0,8.0,14.0,12.0,32.0,16.0,3.0,1.0,37.0,21.0,NaN
4,22500826,2026-02-22 20:00:00,Phoenix,Suns,1610612756,Portland,Trail Blazers,1610612757,1,0.0,77,92,16.0,3.0,14.0,85.0,31.0,0.365,35.0,9.0,0.257,6.0,6.0,1.000,28.0,13.0,41.0,16.0,19.0,-15.0,240.0,20.0,20.0,17.0,20.0,38.0,3.0,6.0,11.0,6.0,25.0,34.0,10.0,6.0,0.0,33.0,25.0,NaN

In [4]:
team_game_stats.describe().round(2)

,gameId,teamId,opponentTeamId,home,win,teamScore,opponentScore,assists,blocks,steals,fieldGoalsAttempted,fieldGoalsMade,fieldGoalsPercentage,threePointersAttempted,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers,plusMinusPoints,numMinutes,q1Points,q2Points,q3Points,q4Points,benchPoints,biggestLead,biggestScoringRun,leadChanges,pointsFastBreak,pointsFromTurnovers,pointsInThePaint,pointsSecondChance,timesTied,timeoutsRemaining,seasonWins,seasonLosses,coachId
count,145628.00,1.456280e+05,1.456280e+05,145628.0,145626.0,145628.00,145628.00,110539.00,104925.00,104481.00,111320.00,145608.00,111239.00,104838.00,115770.00,104131.00,140530.00,145606.00,140524.00,104149.00,104296.00,110882.00,141634.00,104811.00,144616.00,145618.00,4618.00,4606.00,4602.00,4602.0,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,4624.00,0.0
mean,25780539.98,1.610524e+09,1.610524e+09,0.5,0.5,104.20,104.20,23.20,5.00,7.91,84.13,39.55,0.46,19.14,6.20,0.34,26.44,20.17,0.76,30.97,11.80,42.99,22.62,14.88,0.15,226.47,28.74,28.49,28.86,27.5,36.90,13.09,10.16,6.82,15.29,17.74,48.81,14.48,4.97,0.48,16.43,16.45,NaN
std,6404579.70,1.193707e+07,1.193707e+07,0.5,0.5,14.24,14.24,5.64,2.65,3.06,9.07,6.40,0.06,11.26,4.79,0.14,8.73,7.03,0.10,5.63,4.33,7.10,5.16,4.21,13.62,58.95,6.09,6.07,6.25,6.1,14.19,10.11,2.78,5.96,6.56,6.81,10.77,5.91,4.08,0.55,13.25,13.24,NaN
min,10300001.00,0.000000e+00,0.000000e+00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,4.00,0.14,0.00,0.00,0.00,0.00,0.00,0.00,3.00,0.00,0.00,0.00,0.00,-73.00,0.00,8.00,3.00,8.00,8.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
25%,21300746.00,1.610613e+09,1.610613e+09,0.0,0.0,95.00,95.00,19.00,3.00,6.00,78.00,35.00,0.42,11.00,2.00,0.26,20.00,15.00,0.69,27.00,9.00,38.00,19.00,12.00,-9.00,240.00,25.00,24.00,25.00,23.0,27.00,5.00,8.00,2.00,10.00,13.00,42.00,10.00,2.00,0.00,5.00,5.00,NaN
50%,26200124.50,1.610613e+09,1.610613e+09,1.0,0.5,104.00,104.00,23.00,5.00,8.00,84.00,39.00,0.46,17.00,5.00,0.34,26.00,20.00,0.76,31.00,11.00,43.00,22.00,15.00,1.00,240.00,29.00,28.00,29.00,28.0,36.00,11.00,10.00,5.00,15.00,17.00,48.00,14.00,4.00,0.00,14.00,14.00,NaN
75%,28700370.00,1.610613e+09,1.610613e+09,1.0,1.0,114.00,114.00,27.00,7.00,10.00,90.00,44.00,0.50,27.00,9.00,0.43,32.00,25.00,0.82,35.00,14.00,47.00,26.00,18.00,9.00,240.00,33.00,33.00,33.00,32.0,45.00,19.00,12.00,10.00,19.00,22.00,56.00,18.00,7.00,1.00,25.00,25.00,NaN
max,62500001.00,1.610617e+09,1.610617e+09,1.0,1.0,186.00,186.00,89.00,23.00,27.00,240.00,135.00,5.12,70.00,29.00,1.00,91.00,61.00,5.25,60.00,44.00,109.00,122.00,40.00,73.00,365.00,53.00,52.00,52.00,51.0,99.00,64.00,24.00,42.00,46.00,47.00,88.00,43.00,22.00,6.00,68.00,65.00,NaN

In [5]:
team_game_stats.info()

<class 'pandas.DataFrame'>
RangeIndex: 145628 entries, 0 to 145627
Data columns (total 48 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gameId                   145628 non-null  int64
 1   gameDateTimeEst          145628 non-null  str
 2   teamCity                 145612 non-null  str
 3   teamName                 145626 non-null  str
 4   teamId                   145628 non-null  int64
 5   opponentTeamCity         145612 non-null  str
 6   opponentTeamName         145626 non-null  str
 7   opponentTeamId           145628 non-null  int64
 8   home                     145628 non-null  int64
 9   win                      145626 non-null  float64
 10  teamScore                145628 non-null  int64
 11  opponentScore            145628 non-null  int64
 12  assists                  110539 non-null  float64
 13  blocks                   104925 non-null  float64
 14  steals                   104481 non-null  float64
 15  fieldGoalsAttempted      111320 non-null  float64
 16  fieldGoalsMade           145608 non-null  float64
 17  fieldGoalsPercentage     111239 non-null  float64
 18  threePointersAttempted   104838 non-null  float64
 19  threePointersMade        115770 non-null  float64
 20  threePointersPercentage  104131 non-null  float64
 21  freeThrowsAttempted      140530 non-null  float64
 22  freeThrowsMade           145606 non-null  float64
 23  freeThrowsPercentage     140524 non-null  float64
 24  reboundsDefensive        104149 non-null  float64
 25  reboundsOffensive        104296 non-null  float64
 26  reboundsTotal            110882 non-null  float64
 27  foulsPersonal            141634 non-null  float64
 28  turnovers                104811 non-null  float64
 29  plusMinusPoints          144616 non-null  float64
 30  numMinutes               145618 non-null  float64
 31  q1Points                 4618 non-null    float64
 32  q2Points                 4606 non-null    float64
 33  q3Points                 4602 non-null    float64
 34  q4Points                 4602 non-null    float64
 35  benchPoints              4624 non-null    float64
 36  biggestLead              4624 non-null    float64
 37  biggestScoringRun        4624 non-null    float64
 38  leadChanges              4624 non-null    float64
 39  pointsFastBreak          4624 non-null    float64
 40  pointsFromTurnovers      4624 non-null    float64
 41  pointsInThePaint         4624 non-null    float64
 42  pointsSecondChance       4624 non-null    float64
 43  timesTied                4624 non-null    float64
 44  timeoutsRemaining        4624 non-null    float64
 45  seasonWins               4624 non-null    float64
 46  seasonLosses             4624 non-null    float64
 47  coachId                  0 non-null       float64
dtypes: float64(37), int64(6), str(5)
memory usage: 53.3 MB

In [6]:
team_game_advanced.head()

,gameId,teamId,teamCity,teamName,gameType,astPct,astRatio,astTo,availableFlag,defRating,drebPct,eDefRating,eNetRating,eOffRating,ePace,efgPct,gameDate,gameDateTimeEst,home,matchup,min,netRating,offRating,opponentTeamCity,opponentTeamId,opponentTeamName,orebPct,pace,pacePer40,pie,poss,rebPct,teamAbbreviation,teamName_right,tmTovPct,tsPct,win,wl
0,22500742,1610612765,Detroit,Pistons,Regular Season,0.705,23.3,2.38,1.0,84.2,0.736,84.7,40.1,124.7,94.5,0.633,2026-02-06T00:00:00,2026-02-06 19:30:00,1.0,DET vs. NYK,48.0,42.7,126.9,New York,1.610613e+09,Knicks,0.225,94.0,78.33,0.708,93,0.516,DET,NaN,0.140,0.658,1.0,W
1,22500745,1610612757,Portland,Trail Blazers,Regular Season,0.633,20.9,1.72,1.0,110.6,0.735,111.4,16.9,128.3,104.2,0.639,2026-02-06T00:00:00,2026-02-06 22:00:00,1.0,POR vs. MEM,48.0,19.2,129.8,Memphis,1.610613e+09,Grizzlies,0.310,104.0,86.67,0.578,104,0.538,POR,NaN,0.173,0.680,1.0,W
2,22500744,1610612740,New Orleans,Pelicans,Regular Season,0.674,21.2,1.81,1.0,118.6,0.610,119.2,0.1,119.4,98.1,0.631,2026-02-06T00:00:00,2026-02-06 20:00:00,0.0,NOP @ MIN,48.0,4.1,122.7,Minnesota,1.610613e+09,Timberwolves,0.282,97.0,80.83,0.540,97,0.480,NOP,NaN,0.165,0.663,1.0,W
3,22500746,1610612746,LA,Clippers,Regular Season,0.595,16.9,1.38,1.0,114.4,0.679,110.3,6.3,116.5,99.3,0.585,2026-02-06T00:00:00,2026-02-06 22:00:00,0.0,LAC @ SAC,48.0,0.7,115.2,Sacramento,1.610613e+09,Kings,0.225,98.0,81.67,0.537,99,0.484,LAC,NaN,0.162,0.656,1.0,W
4,22500743,1610612754,Indiana,Pacers,Regular Season,0.743,20.6,2.89,1.0,114.1,0.654,108.7,-1.3,107.3,94.4,0.519,2026-02-06T00:00:00,2026-02-06 20:00:00,0.0,IND @ MIL,48.0,-7.7,106.5,Milwaukee,1.610613e+09,Bucks,0.152,92.5,77.08,0.513,93,0.418,IND,NaN,0.097,0.561,0.0,L

In [7]:
team_game_advanced.info()

<class 'pandas.DataFrame'>
RangeIndex: 10258 entries, 0 to 10257
Data columns (total 38 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gameId            10258 non-null  int64
 1   teamId            10258 non-null  int64
 2   teamCity          9990 non-null   str
 3   teamName          9990 non-null   str
 4   gameType          10254 non-null  str
 5   astPct            10258 non-null  float64
 6   astRatio          10258 non-null  float64
 7   astTo             10258 non-null  float64
 8   availableFlag     5266 non-null   float64
 9   defRating         10258 non-null  float64
 10  drebPct           9511 non-null   float64
 11  eDefRating        10258 non-null  float64
 12  eNetRating        10258 non-null  float64
 13  eOffRating        10258 non-null  float64
 14  ePace             10258 non-null  float64
 15  efgPct            10258 non-null  float64
 16  gameDate          10258 non-null  str
 17  gameDateTimeEst   9990 non-null   str
 18  home              9990 non-null   float64
 19  matchup           10246 non-null  str
 20  min               10258 non-null  float64
 21  netRating         10258 non-null  float64
 22  offRating         10258 non-null  float64
 23  opponentTeamCity  9990 non-null   str
 24  opponentTeamId    9990 non-null   float64
 25  opponentTeamName  9990 non-null   str
 26  orebPct           9512 non-null   float64
 27  pace              10258 non-null  float64
 28  pacePer40         10258 non-null  float64
 29  pie               10258 non-null  float64
 30  poss              10258 non-null  int64
 31  rebPct            8876 non-null   float64
 32  teamAbbreviation  10258 non-null  str
 33  teamName_right    0 non-null      float64
 34  tmTovPct          10258 non-null  float64
 35  tsPct             10258 non-null  float64
 36  win               9990 non-null   float64
 37  wl                10254 non-null  str
dtypes: float64(25), int64(3), str(10)
memory usage: 3.0 MB

In [8]:
team_games = pd.merge(
    team_game_advanced,
    team_game_stats,
    on=["gameId", "teamId"],
    how="inner",
    suffixes=("_adv", "_basic"),
)

team_games.info()

<class 'pandas.DataFrame'>
RangeIndex: 9990 entries, 0 to 9989
Data columns (total 84 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   gameId                   9990 non-null   int64
 1   teamId                   9990 non-null   int64
 2   teamCity_adv             9990 non-null   str
 3   teamName_adv             9990 non-null   str
 4   gameType                 9986 non-null   str
 5   astPct                   9990 non-null   float64
 6   astRatio                 9990 non-null   float64
 7   astTo                    9990 non-null   float64
 8   availableFlag            5168 non-null   float64
 9   defRating                9990 non-null   float64
 10  drebPct                  9265 non-null   float64
 11  eDefRating               9990 non-null   float64
 12  eNetRating               9990 non-null   float64
 13  eOffRating               9990 non-null   float64
 14  ePace                    9990 non-null   float64
 15  efgPct                   9990 non-null   float64
 16  gameDate                 9990 non-null   str
 17  gameDateTimeEst_adv      9990 non-null   str
 18  home_adv                 9990 non-null   float64
 19  matchup                  9990 non-null   str
 20  min                      9990 non-null   float64
 21  netRating                9990 non-null   float64
 22  offRating                9990 non-null   float64
 23  opponentTeamCity_adv     9990 non-null   str
 24  opponentTeamId_adv       9990 non-null   float64
 25  opponentTeamName_adv     9990 non-null   str
 26  orebPct                  9266 non-null   float64
 27  pace                     9990 non-null   float64
 28  pacePer40                9990 non-null   float64
 29  pie                      9990 non-null   float64
 30  poss                     9990 non-null   int64
 31  rebPct                   8652 non-null   float64
 32  teamAbbreviation         9990 non-null   str
 33  teamName_right           0 non-null      float64
 34  tmTovPct                 9990 non-null   float64
 35  tsPct                    9990 non-null   float64
 36  win_adv                  9990 non-null   float64
 37  wl                       9986 non-null   str
 38  gameDateTimeEst_basic    9990 non-null   str
 39  teamCity_basic           9990 non-null   str
 40  teamName_basic           9990 non-null   str
 41  opponentTeamCity_basic   9990 non-null   str
 42  opponentTeamName_basic   9990 non-null   str
 43  opponentTeamId_basic     9990 non-null   int64
 44  home_basic               9990 non-null   int64
 45  win_basic                9990 non-null   float64
 46  teamScore                9990 non-null   int64
 47  opponentScore            9990 non-null   int64
 48  assists                  9990 non-null   float64
 49  blocks                   9990 non-null   float64
 50  steals                   9990 non-null   float64
 51  fieldGoalsAttempted      9990 non-null   float64
 52  fieldGoalsMade           9990 non-null   float64
 53  fieldGoalsPercentage     9990 non-null   float64
 54  threePointersAttempted   9990 non-null   float64
 55  threePointersMade        9990 non-null   float64
 56  threePointersPercentage  9990 non-null   float64
 57  freeThrowsAttempted      9990 non-null   float64
 58  freeThrowsMade           9990 non-null   float64
 59  freeThrowsPercentage     9990 non-null   float64
 60  reboundsDefensive        9990 non-null   float64
 61  reboundsOffensive        9990 non-null   float64
 62  reboundsTotal            9990 non-null   float64
 63  foulsPersonal            9990 non-null   float64
 64  turnovers                9990 non-null   float64
 65  plusMinusPoints          9920 non-null   float64
 66  numMinutes               9986 non-null   float64
 67  q1Points                 2004 non-null   float64
 68  q2Points                 2004 non-null   float64
 69  q3Points                 2002 non-null   float64
 70  q4Points                 2002 non-null   float64
 71  benchPoints              2004 non-null   float64
 72  biggestLead              2004 non-null   float64
 73  biggestScoringRun        2004 non-null   float64
 74  leadChanges              2004 non-null   float64
 75  pointsFastBreak          2004 non-null   float64
 76  pointsFromTurnovers      2004 non-null   float64
 77  pointsInThePaint         2004 non-null   float64
 78  pointsSecondChance       2004 non-null   float64
 79  timesTied                2004 non-null   float64
 80  timeoutsRemaining        2004 non-null   float64
 81  seasonWins               2004 non-null   float64
 82  seasonLosses             2004 non-null   float64
 83  coachId                  0 non-null      float64
dtypes: float64(62), int64(7), str(15)
memory usage: 6.4 MB

In [10]:
team_games.columns.tolist()

['gameId',
 'teamId',
 'teamCity_adv',
 'teamName_adv',
 'gameType',
 'astPct',
 'astRatio',
 'astTo',
 'availableFlag',
 'defRating',
 'drebPct',
 'eDefRating',
 'eNetRating',
 'eOffRating',
 'ePace',
 'efgPct',
 'gameDate',
 'gameDateTimeEst_adv',
 'home_adv',
 'matchup',
 'min',
 'netRating',
 'offRating',
 'opponentTeamCity_adv',
 'opponentTeamId_adv',
 'opponentTeamName_adv',
 'orebPct',
 'pace',
 'pacePer40',
 'pie',
 'poss',
 'rebPct',
 'teamAbbreviation',
 'teamName_right',
 'tmTovPct',
 'tsPct',
 'win_adv',
 'wl',
 'gameDateTimeEst_basic',
 'teamCity_basic',
 'teamName_basic',
 'opponentTeamCity_basic',
 'opponentTeamName_basic',
 'opponentTeamId_basic',
 'home_basic',
 'win_basic',
 'teamScore',
 'opponentScore',
 'assists',
 'blocks',
 'steals',
 'fieldGoalsAttempted',
 'fieldGoalsMade',
 'fieldGoalsPercentage',
 'threePointersAttempted',
 'threePointersMade',
 'threePointersPercentage',
 'freeThrowsAttempted',
 'freeThrowsMade',
 'freeThrowsPercentage',
 'reboundsDefensive',
 'reboundsOffensive',
 'reboundsTotal',
 'foulsPersonal',
 'turnovers',
 'plusMinusPoints',
 'numMinutes',
 'q1Points',
 'q2Points',
 'q3Points',
 'q4Points',
 'benchPoints',
 'biggestLead',
 'biggestScoringRun',
 'leadChanges',
 'pointsFastBreak',
 'pointsFromTurnovers',
 'pointsInThePaint',
 'pointsSecondChance',
 'timesTied',
 'timeoutsRemaining',
 'seasonWins',
 'seasonLosses',
 'coachId']

In [ ]:
print(team_game_stats.head(10))

In [13]:
print(team_game_advanced.head(10))

     gameId      teamId     teamCity       teamName        gameType  astPct  \
0  22500742  1610612765      Detroit        Pistons  Regular Season   0.705
1  22500745  1610612757     Portland  Trail Blazers  Regular Season   0.633
2  22500744  1610612740  New Orleans       Pelicans  Regular Season   0.674
3  22500746  1610612746           LA       Clippers  Regular Season   0.595
4  22500743  1610612754      Indiana         Pacers  Regular Season   0.743
5  22500741  1610612738       Boston        Celtics  Regular Season   0.486
6  22500741  1610612748        Miami           Heat  Regular Season   0.657
7  22500743  1610612749    Milwaukee          Bucks  Regular Season   0.591
8  22500746  1610612758   Sacramento          Kings  Regular Season   0.537
9  22500744  1610612750    Minnesota   Timberwolves  Regular Season   0.550

   astRatio  astTo  availableFlag  defRating  drebPct  eDefRating  eNetRating  \
0      23.3   2.38            1.0       84.2    0.736        84.7        40.1
1      20.9   1.72            1.0      110.6    0.735       111.4        16.9
2      21.2   1.81            1.0      118.6    0.610       119.2         0.1
3      16.9   1.38            1.0      114.4    0.679       110.3         6.3
4      20.6   2.89            1.0      114.1    0.654       108.7        -1.3
5      13.4   1.06            1.0      103.2    0.736       102.2        -1.3
6      17.8   1.92            1.0      106.5    0.654       100.9         1.3
7      19.1   2.17            1.0      106.5    0.848       107.3         1.3
8      16.2   2.00            1.0      115.2    0.775       116.5        -6.3
9      15.5   2.20            1.0      122.7    0.718       119.4        -0.1

   eOffRating  ePace  efgPct             gameDate      gameDateTimeEst  home  \
0       124.7   94.5   0.633  2026-02-06T00:00:00  2026-02-06 19:30:00   1.0
1       128.3  104.2   0.639  2026-02-06T00:00:00  2026-02-06 22:00:00   1.0
2       119.4   98.1   0.631  2026-02-06T00:00:00  2026-02-06 20:00:00   0.0
3       116.5   99.3   0.585  2026-02-06T00:00:00  2026-02-06 22:00:00   0.0
4       107.3   94.4   0.519  2026-02-06T00:00:00  2026-02-06 20:00:00   0.0
5       100.9   95.5   0.476  2026-02-06T00:00:00  2026-02-06 19:30:00   1.0
6       102.2   95.5   0.494  2026-02-06T00:00:00  2026-02-06 19:30:00   0.0
7       108.7   94.4   0.532  2026-02-06T00:00:00  2026-02-06 20:00:00   1.0
8       110.3   99.3   0.500  2026-02-06T00:00:00  2026-02-06 22:00:00   1.0
9       119.2   98.1   0.489  2026-02-06T00:00:00  2026-02-06 20:00:00   1.0

       matchup   min  netRating  offRating opponentTeamCity  opponentTeamId  \
0  DET vs. NYK  48.0       42.7      126.9         New York    1.610613e+09
1  POR vs. MEM  48.0       19.2      129.8          Memphis    1.610613e+09
2    NOP @ MIN  48.0        4.1      122.7        Minnesota    1.610613e+09
3    LAC @ SAC  48.0        0.7      115.2       Sacramento    1.610613e+09
4    IND @ MIL  48.0       -7.7      106.5        Milwaukee    1.610613e+09
5  BOS vs. MIA  48.0        3.3      106.5            Miami    1.610613e+09
6    MIA @ BOS  48.0       -3.3      103.2           Boston    1.610613e+09
7  MIL vs. IND  48.0        7.7      114.1          Indiana    1.610613e+09
8  SAC vs. LAC  48.0       -0.7      114.4               LA    1.610613e+09
9  MIN vs. NOP  48.0       -4.1      118.6      New Orleans    1.610613e+09

  opponentTeamName  orebPct   pace  pacePer40    pie  poss  rebPct  \
0           Knicks    0.225   94.0      78.33  0.708    93   0.516
1        Grizzlies    0.310  104.0      86.67  0.578   104   0.538
2     Timberwolves    0.282   97.0      80.83  0.540    97   0.480
3            Kings    0.225   98.0      81.67  0.537    99   0.484
4            Bucks    0.152   92.5      77.08  0.513    93   0.418
5             Heat    0.346   92.5      77.08  0.502    92   0.543
6          Celtics    0.264   92.5      77.08  0.498    93   0.457
7           Pacers    0.346   92.5      77.08  0.487    92   0.582
8         Clippers    0.321   98.0      81.67  0.463    97   0.516
9         Pelicans    0.390   97.0      80.83  0.460    97   0.520

  teamAbbreviation  teamName_right  tmTovPct  tsPct  win wl
0              DET             NaN     0.140  0.658  1.0  W
1              POR             NaN     0.173  0.680  1.0  W
2              NOP             NaN     0.165  0.663  1.0  W
3              LAC             NaN     0.162  0.656  1.0  W
4              IND             NaN     0.097  0.561  0.0  L
5              BOS             NaN     0.174  0.521  1.0  W
6              MIA             NaN     0.129  0.522  0.0  L
7              MIL             NaN     0.130  0.538  1.0  W
8              SAC             NaN     0.113  0.546  0.0  L
9              MIN             NaN     0.103  0.540  0.0  L